# Generated by Django 4.0.5 on 2023-07-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciesWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.IntegerField(max_length=100)),
                ('level', models.CharField(max_length=2)),
                ('expression', models.BooleanField()),
            ],
        ),
    ]
