# Generated by Django 4.0.5 on 2023-07-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencies_words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencieswords',
            name='percent',
            field=models.IntegerField(),
        ),
    ]
